baseURL = "http://example.org/"
languageCode = "en-us"
title = "bpanthi977"
theme = "ananke"

paginate = 3
enableEmoji ="true"
sectionPagesMenu = "main"

[params]
  background_color_class = "bg-grey"
  recent_posts_number = 2	
