* Episode 2 Transcript
  :PROPERTIES:
  :ID:       8769a03f-d2bf-4999-a15a-b4aadbd57bce
  :END:
This is a transcript of Episode 2 on Italian Pre-Socratic Philosophy.

If you're like me, when you hear the name Pythagoras you probably think of, the Pythagorean theorem.

His love of mathematics and astronomy probably began when he was young when he visited Egypt and Miletus, and its not farfetched to think that he would've studied under the Milesian school of thought, remember that's where Thales and Anaxamander came from that we talked about last episode.

Around the age of 40, he started gathering together these followers who saw him as a religious sage, and set up a commune in a town called Croton, in southern Italy.

A few different sources say when he first started up he had around 300 members of this commune and everything he's known for comes from the work he did when he was inside of this commune, and because of how unclear it is whether he himself came up with any ONE theory or whether it was one of his followers attributing it to his master...the brains behind the operation, historians just kind of lump everything under this one umbrella of Pythagoreanism. And this applies to everything, even the famous Pythagorean theorem itself.

The world philosopher means lover of wisdom. 'philo' means love, 'soph' means wisdom, and Pythagoras himself was actually the first guy to coin the term.

 You know how there's IQ which is your intelligence quotient and then there’s NQ which is your networking quotient, or your ability to interact socially and influence people? Pythagoras was no doubt a genius in both of these areas. I mean, this commune wasn’t like, hey come live in a village with us and study math every once in a while. This was a complete lifestyle overhaul. and a restrictive overhaul at that. Not only was it dedicating your entire life to the pursuit of knowledge in math, music and astronomy, the 3 areas they saw as the most important those were only half of it. The other half was the religious side of the cult and all the behavioral restrictions.

We take so many things for granted today that are explained in modern physics and chemistry that they had no idea about, so to realize that adding together the squares of two sides of a right triangle was equal to the square of the hypotenuse...that was cool. But to realize...that applies to all right triangles and there are no exceptions to that rule...and to feel that you really understand something about the essence of that triangle and the laws that govern the sides of that triangle or any triangle in the universe? That must have been...mind numbing.

They saw these mathematical proofs as the way the universe could be understood, or as they put it, number is the ruler of all forms.


... its also to see how a man like Pythagoras, the messenger boy arriving at these conclusions could have seemed like a demigod himself.

whenever i think of this concept I love to contrast it with the fact that the SAME information that was so powerful it made a man believe he was a messiah in a religious movement 2500 years ago, is the midterm for 7th grade pre-algebra in today's world.

It really is a testament to human progress and just how far we've come as a species. and how about a testament to how far were capable of going.

Pythagoras found that harmonies that we hear all the time, even in music today were just simple mathematical ratios

when it came to reincarnation, the Pythagoreans believed that this cycle of constantly dying and being reincarnated into a new body was some sort of punishment, and that the goal of life was to end the cycle of reincarnation and finally be set free to live eternally in the blessed realm...either the sun or the moon

for Pythagoras the thought portion of this was math music and astronomy. so why did he pick those concepts as opposed to something else? because the understanding of those topics led to the understanding of the universal truths that govern the universe. eternal truths...truths that never change.

And its pretty awesome to think about it the way they did...they thought that the closest thing a person can achieve to immortality is to understand these eternal truths and to try to live in harmony with them. by understanding concepts that are eternal, that’s the closest man will ever get to being immortal.A

One other very notable contribution is he was the first one to make the statement that arriving to conclusions through reason was greatly superior to evidence gathered through the senses.

There have been hundreds of _rationalist_ philosophers that would go on to arrive at notable conclusions themselves, but one of the best examples of this was Plato and the idea of using reason to arrive at conclusions was the BASIS of his super famous theory of forms. 

Anyway, onto his deductive reasoning and how it changed philosophy. His idea was actually pretty simple, but he phrases it in a way that makes it a little difficult to follow.

 He says...what is is....and what is not is not...in other words if something exists it exists if something does not exist it does not exist and its impossible for something to exist and not exist at the same time right? he says that because of this, a point in time where the universe was in a state of nothing existing is impossible because things exist now and nothing can come into existence from a place where nothing exists.

 In other words, something cannot come from nothing and so the universe must have always existed in some form and is eternal. 

If the universe came into existence... what caused it to come into existence in the first place? what made it start then as opposed to earlier or later? Philosophers hadn't really thought of this before, they were content with accepting that...they were here and it did exist and everything has a beginning, so lets try to think of some interesting explanations for how it happened that don't involve gods. He also thought that we cannot speak of what "is not" or what doesn't exist. For example, to think about a unicorn is to essentially think about nothing...because it doesn't exist. To talk about a unicorn, to Parmenides is just to be making meaningless sound, because it doesn’t exist. 

 With Democritus and Leucippus it was their atoms like we talked about last episode, with the Pythagoreans it was numbers and harmony, but in the case of Parmenides its pretty extreme. he basically is saying that although we see motion and change and birth and death...that none of it is actually happening. which completely contradicts what we see. not to mention, hes saying we cant speak of "what is not"...but by talking about the fact that birth, death motion or change, he IS speaking of "what is not". and that just doesn’t make any sense Parmenides.

he would’ve said, yeah, you think you're speaking of something that doesn’t exist but really you’re just talking about nothing, you should abandon these "common sense prejudices" you have. see, the fact you think you're talking about something that doesn’t exist is based on evidence you’ve gathered through the sense organs, if what you think you see with your senses and what reason tells you contradicts each other...reason should always be held in higher regard because the senses are deceptive and cant be trusted.


Like Atomism.Empedocles was one of these philosophers that added into parmenides. he thought that the whole world was made up of 4 elements that were in themselves eternal and unchanging, but added that they had the ability to combine with each other to make up the changing world we see.According to Empedocles, he was an immortal god among men who had been given his divine status because of all the knowledge he had gained through extensive thought during his life. He would walk around everywhere in this ridiculous outfit, a purple robe, a giant golden belt, bronze shoes, and a wreath around his head like he was the Delphic oracle. And he did it on purpose...he said when he walks through a new town, he wants people to see him and wonder what hes all about and follow him around in the thousands...and it WORKED.Anyone that didn't agree with him or questioned him were complete fools.You see, he was a god and he knew of a time a long time ago when man experienced a golden age when all men lived happily together and there was no turmoil in the world. The bad news was all men at first were gods, they just lost their immortal status and were put here on earth. the good news was they all had the ability to become gods again, they just had to live the right way. Only through knowledge and following Empedocles could men can regain the divine status they once had.Like I said before, he agreed with parmenides that the universe is eternal and that nothing is ever created or destroyed. He just tried to find a compromise that would account for the seemingly changing world that we see everyday with our sense organs.He claimed there were four elements. Air, Water, Fire and Earth and that all things are just different recipes of different quantities of these four elements. Combine his ridiculous super-hero like getup, with his Earth, Fire, Wind and Water with his views on the forces of love and strife that I’ll talk about later and he begins to sound pretty familiar.captain planet theme songEmpedocles is Captain Planet. At least that's how I remember him. For anyone that is incredibly confused right now, let me explain. Captain Planet was a cartoon from the early nineties. where a group of teenagers all had the power to summon a superhero named captain planet. each one of them had a ring. there were 5 different things they called out and then a double rainbow of light shot out of their rings and captain planet arrived. these were earth, fire, wind, water and heart.If Captain Planet has any emotional context for you, it is an extremely effective way to remember Empedocles. Like I said, the crazy super-hero like getup, his views of earth fire air and water and heart symbolizing his thoughts on the forces of love and strife that we will talk about in a little. If Captain planet holds no significance to you, i humbly apologize for wasting 30 seconds of your life, and maybe consider checking out a few episodes for comedic value, you just don’t see cartoons that deliver a positive message like that to kids anymore.Empedocles thought the elements, earth fire air and water, themselves do not change, they just intermingle and move around and combine with each other. This was the compromise Empedocles made to Parmenides' extreme idea that change and movement is impossible. Empedocles said that the process of the elements intermingling and moving around is what man calls "birth" or death. birth and death are just human constructs, or words, used to define different assemblies of unchanging things. this has a lot of similarities with the idea of atomism that we were talking about last episode. remember, the atoms themselves do not change, just the configuration of atoms.he saw the mixing of the different elements as similar to the mixing of colors of paint that an artist would have, when you look at a cup, you’re really just looking at nature's masterful combination of these 4 elements. and this applied to anything you can see around you. what about metals? he had bronze shoes after all. all metals were actually seen as water because they could be melted down and combined with other metals.“As painters, men well taught by wisdom in the practice of their art, decorate temple offerings they take in their hands pigments of various colors, and after fitting them in close combination, more of some and less of others, they produce from them shapes resembling all things, creating trees and men and women, animals and birds and water-nourished fish, and long-lived gods too, highest in honour; so let not error convince you in your mind that there is any other source for the countless perishables that are seen, but know this clearly, since the discourse you have heard is from a god."i like how, just for good measure he adds on at the end...by the way I'm a god so trust me. Just in case you guys didn't agree with the mixing of paint analogy I just made...as you’ve probably noticed he was pretty similar to Pythagoras in several ways. He WAS a Pythagorean. He believed in reincarnation. He believed that there were two forces in the universe that were constantly at battle with one another. One of them was love, which not only is responsible for bringing the elements together to make up the everyday items we see, but is responsible for human emotion, this force of love is actually what caused humans to feel sexual attraction towards each other...the other force was strife, which constantly seeks to drive the elements apart and break them down and in the case of humans its what drives people away from each other and creates problems. love and strife are constantly at battle with one another and the result of this constant battle is the changing world we perceive.see, he thought a long time ago, there was a time when love reigned supreme...it had triumphed over strife completely and all the elements were all in one sphere with love protecting them, in the middle of the universe...but then strife started attacking love and the elements got out of this protective sphere and were scatted around everywhere...and then love fought back and started grouping the elements back together, in the process, as these small quantities of elements are drawn together by love, the everyday things we see like mountains, and trees and chairs were assembled. In the current state of the world, love and strife are constantly battling one another..love combines the elements into a human or a dog and then strife tears it apart and makes it into ashes... eventually, a long time from now Empedocles says that one of them, either love or strife, will reign supreme and the entire process will start over again.well, its a wonderful story and all, but the thing that makes it important to philosophy is that it was the first time anyone had thought of the idea of there being an intangible force responsible for the actions of the elements. before, if the whole world was made up of varying different forms of water, water itself doesn’t move right? how can you explain the fact it somehow manifested itself into all this stuff? the idea of a force being behind it was revolutionary and incredibly insightful and similar to what we know of forces in modern physics.He also seems to have accurately arrived at the idea of natural selection as being the way animals survived and adapted. they owe the features that allow them to survive to the fact that there used to be MANY different species of creatures and the ones with characteristics that didn’t behoove them died off before they were able to propagate...leaving only the strongest and best adapted. quote" here sprang up many faces without necksOne last way you can think of Empedocles as Captain Planet is that he was a huge proponent of recycling, but not recycling cans and bottles...but ideas. He really was a giant conglomeration of several great ideas that were successful for previous philosophers in their own time. He was like Pythagoras being the crazy demigod, and he also had a whole religious message to his philosophy that was similar to Pythagoras...basically it was a positive message about living with the ways of love as opposed to strife and that all men are being punished in their current form because they sacrificed animals and ate meat. His constant battling spectrum is like the flux theory of Heraclitus. His compromise on Parmenides eternal universe being very similar to Democritus' theory on atoms, although he was a contemporary of Democritus.Anyway, legend has it that eventually Empedocles jumped into a volcano to prove that he was immortal, i don’t have to tell you how that one worked out for him. but he left the world an accomplished man who came up with a theory of what everything around us is made of that was so successful that Aristotle himself heavily endorsed it with only a few corrections and it was widely seen as the truth until 18th century.
